cesm2:

  raw_root: "/scratch/zgp2ps/cesm2/data/"
  landmask_root: "/scratch/zgp2ps/cesm2/landmask/"
  # fixed configs
  input_vars: [
    "U200", "V200", "U500", "V500", "OMEGA500", "U850", "V850",
    "Z200", "Z500", "Z850", "PSL",
    "TS", "T200", "T500", "T850", "FLUT",
    "TMQ", "Q200", "Q500", "Q850",
    "PRECT",
  ] # order matters
  output_vars: ["PRECT"]
  resolution: [192, 288]
  # NOTE: `sim_ids` can be selected individually for exportdata.py
  sim_ids: [
    # Boundary condition: BHISTsmbb
    "1011.001",
    "1031.002",
    "1051.003",
    "1071.004",
    "1091.005",
    "1111.006",
    "1131.007",
    "1151.008",
    "1171.009",
    "1191.010",
    "1231.011",
    "1251.011",
    "1281.011",
    "1301.011",
    # # Boundary condition: BHISTcmip6
    # "1001.001",
    # "1021.002",
    # "1041.003",
    # "1061.004",
    # "1081.005",
    # "1101.006",
    # "1121.007",
    # "1141.008",
    # "1161.009",
    # "1181.010",
    # "1231.001",
    # "1251.001",
    # "1281.001",
    # "1301.001",
  ]
  # modifiable configs:
  train_start_year: 1950
  train_end_year: 2000
  val_start_year: 2001
  val_end_year: 2010
  test_start_year: 2011
  test_end_year: 2014

  n_input_days: 28
  n_lead_days: 14
  n_output_days: 14
  n_step_days: 14
  climatological_window_size: 15

  train_write_directory: "/scratch/zgp2ps/cesm2/tensors/train/"
  val_write_directory: "/scratch/zgp2ps/cesm2/tensors/val/"
  test_write_directory: "/scratch/zgp2ps/cesm2/tensors/test/"
  detrender_state_directory: "/scratch/zgp2ps/cesm2/tensors/detrender/"
  climatology_state_directory: "/scratch/zgp2ps/cesm2/tensors/climatology/"


era5:

  raw_root: "/scratch/zgp2ps/era5/raw/"
  array_root: "/scratch/zgp2ps/era5/arrays/"
  landmask_root: "/scratch/zgp2ps/era5/raw/landmask/"
  # fixed configs
  input_vars: [
    "u200", "v200", "u500", "v500", "w500", "u850", "v850",
    "z200", "z500", "z850", "msl",
    "skt", "t200", "t500", "t850", "avgtnlwrf",
    "tcwv", "q200", "q500", "q850",
    "tp",
  ] # order matters
  output_vars: ["tp"]
  resolution: [192, 288]
  sim_ids: ["reanalysis"]
  # modifiable configs:
  train_start_year: 1940
  train_end_year: 2010
  val_start_year: 2011
  val_end_year: 2020
  test_start_year: 2021
  test_end_year: 2025

  n_input_days: 28
  n_lead_days: 14
  n_output_days: 14
  n_step_days: 14
  climatological_window_size: 15

  train_write_directory: "/scratch/zgp2ps/era5/tensors/train/"
  train_metadata_directory: "/scratch/zgp2ps/era5/tensors/train/metadata/"
  val_write_directory: "/scratch/zgp2ps/era5/tensors/val/"
  val_metadata_directory: "/scratch/zgp2ps/era5/tensors/val/metadata/"
  test_write_directory: "/scratch/zgp2ps/era5/tensors/test/"
  test_metadata_directory: "/scratch/zgp2ps/era5/tensors/test/metadata/"
  detrender_state_directory: "/scratch/zgp2ps/era5/tensors/detrender/"
  climatology_state_directory: "/scratch/zgp2ps/era5/tensors/climatology/"


cnn:

  in_features: 21
  out_features: 1
  embedding_dim: 1024
  n_hidden_layers: 12

  learning_rate: 1e-6
  train_batch_size: 4
  val_batch_size: 1

  n_epochs: 1000
  patience: 10
  tolerance: 0.
  save_frequency: 1

  from_checkpoint: null
  saved_checkpoint_directory: "/scratch/zgp2ps/s2s_checkpoints/train_era5/cnn_large/"
  # inference
  target_path: "/scratch/zgp2ps/s2s_results/train_era5/cnn_large/"


unet:

  in_features: 21
  out_features: 1
  embedding_dim: 512

  learning_rate: 1e-5
  train_batch_size: 4
  val_batch_size: 4
  n_epochs: 1000
  patience: 10
  tolerance: 0.
  save_frequency: 1

  from_checkpoint: null
  saved_checkpoint_directory: "/scratch/zgp2ps/s2s_checkpoints/train_era5/unet_large/"
  # inference
  target_path: "/scratch/zgp2ps/s2s_results/train_era5/unet_large/"


vit:

  in_features: 21
  out_features: 1
  embedding_dim: 256
  patch_size: 32
  n_heads: 8
  n_transformer_layers: 6
  dropout: 0.1

  learning_rate: 1e-5
  train_batch_size: 4
  val_batch_size: 4
  n_epochs: 1000
  patience: 10
  tolerance: 0.
  save_frequency: 1

  from_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/vit/vit3.pt"
  saved_checkpoint_directory: "/scratch/zgp2ps/s2s_checkpoints/vit/"
  # inference
  target_path: "/scratch/zgp2ps/s2s_results/vit/"


vae-wind:

  latent_dim: 28
  hidden_dim: 128
  n_scaling_blocks: 3
  n_convstack_layers: 8
  n_convhead_layers: 4

  lambda: 1.
  learning_rate: 1e-5
  train_batch_size: 32
  val_batch_size: 32
  n_epochs: 1000
  patience: 10
  tolerance: 0.
  save_frequency: 1

  # from_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/train_cesm2/vae_wind_16times/vaewind6.pt"
  # saved_checkpoint_directory: "/scratch/zgp2ps/s2s_checkpoints/train_cesm2/vae_wind_16times/"
  # target_path: "/scratch/zgp2ps/s2s_results/train_cesm2/vae_wind_16times/"

  from_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/train_era5/vae_wind_16times/vaewind34.pt"
  saved_checkpoint_directory: "/scratch/zgp2ps/s2s_checkpoints/train_era5/vae_wind_16times/"
  target_path: "/scratch/zgp2ps/s2s_results/train_era5/vae_wind_16times/"


vae-mass:

  latent_dim: 16
  hidden_dim: 128
  n_scaling_blocks: 3
  n_convstack_layers: 8
  n_convhead_layers: 4

  lambda: 1.
  learning_rate: 1e-6
  train_batch_size: 32
  val_batch_size: 32
  n_epochs: 1000
  patience: 10
  tolerance: 0.
  save_frequency: 1

  # from_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/train_cesm2/vae_mass_16times/vaemass11.pt"
  # saved_checkpoint_directory: "/scratch/zgp2ps/s2s_checkpoints/train_cesm2/vae_mass_16times/"
  # target_path: "/scratch/zgp2ps/s2s_results/train_cesm2/vae_mass_16times/"

  from_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/train_era5/vae_mass_16times/vaemass228.pt"
  saved_checkpoint_directory: "/scratch/zgp2ps/s2s_checkpoints/train_era5/vae_mass_16times/"
  target_path: "/scratch/zgp2ps/s2s_results/train_era5/vae_mass_16times/"


vae-thermal:

  latent_dim: 20
  hidden_dim: 128
  n_scaling_blocks: 3
  n_convstack_layers: 8
  n_convhead_layers: 4

  lambda: 1.
  learning_rate: 1e-4
  train_batch_size: 32
  val_batch_size: 32
  n_epochs: 1000
  patience: 10
  tolerance: 0.
  save_frequency: 1

  # from_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/train_cesm2/vae_thermal_16times/vaethermal15.pt"
  # saved_checkpoint_directory: "/scratch/zgp2ps/s2s_checkpoints/train_cesm2/vae_thermal_16times/"
  # target_path: "/scratch/zgp2ps/s2s_results/train_cesm2/vae_thermal_16times/"

  from_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/train_era5/vae_thermal_16times/vaethermal196.pt"
  saved_checkpoint_directory: "/scratch/zgp2ps/s2s_checkpoints/train_era5/vae_thermal_16times/"
  target_path: "/scratch/zgp2ps/s2s_results/train_era5/vae_thermal_16times/"


vae-hydro:

  latent_dim: 16
  hidden_dim: 128
  n_scaling_blocks: 3
  n_convstack_layers: 8
  n_convhead_layers: 4

  lambda: 1.
  learning_rate: 1e-4
  train_batch_size: 32
  val_batch_size: 32
  n_epochs: 1000
  patience: 10
  tolerance: 0.
  save_frequency: 1

  # from_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/train_cesm2/vae_hydro_16times/vaehydro3.pt"
  # saved_checkpoint_directory: "/scratch/zgp2ps/s2s_checkpoints/train_cesm2/vae_hydro_16times/"
  # target_path: "/scratch/zgp2ps/s2s_results/train_cesm2/vae_hydro_16times/"

  from_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/train_era5/vae_hydro_16times/vaehydro48.pt"
  saved_checkpoint_directory: "/scratch/zgp2ps/s2s_checkpoints/train_era5/vae_hydro_16times/"
  target_path: "/scratch/zgp2ps/s2s_results/train_era5/vae_hydro_16times/"


vae-precip:

  latent_dim: 16
  hidden_dim: 128
  n_scaling_blocks: 3
  n_convstack_layers: 8
  n_convhead_layers: 4

  lambda: 0.999
  learning_rate: 1e-6
  train_batch_size: 32
  val_batch_size: 32
  n_epochs: 1000
  patience: 10
  tolerance: 0.
  save_frequency: 1

  # from_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/train_cesm2/vae_precip_4times/vaeprecip6.pt"
  # saved_checkpoint_directory: "/scratch/zgp2ps/s2s_checkpoints/train_cesm2/vae_precip_4times/"
  # target_path: "/scratch/zgp2ps/s2s_results/train_cesm2/vae_precip_4times/"

  from_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/train_era5/vae_precip_4times/vaeprecip41.pt"
  saved_checkpoint_directory: "/scratch/zgp2ps/s2s_checkpoints/train_era5/vae_precip_4times/"
  target_path: "/scratch/zgp2ps/s2s_results/train_era5/vae_precip_4times/"


diffusion:

  target_dim: 16  # fixed, vae-precip.latent_dim
  condition_dim: 96  # fixed, vae-wind.latent_dim + vae-mass.latent_dim + vae-thermal.latent_dim + vae-hydro.latent_dim + vae-precip.latent_dim
  # Denoiser configurations
  down_out_dims: [256, 512]
  mid_out_dims: [512, 512]
  up_out_dims: [512, 256]   # effective dim before transformer: up_out_dims[-1]
  down_transformer_model_dims: [256, 256]
  mid_transformer_model_dims: [256, 256]
  up_transformer_model_dims: [256, 256]
  n_conv_layers_per_scaling_block: 6
  n_transformer_encoder_layers_per_scaling_block: 6
  n_transformer_decoder_layers_per_scaling_block: 6
  n_conv_layers_per_mid_block: 3
  n_transformer_encoder_layers_per_mid_block: 6
  n_transformer_decoder_layers_per_mid_block: 6
  transformer_feedforward_dim: 2048
  n_attention_heads: 4
  transformer_maxlength: 28   # must be >= max(dataset.n_input_days, dataset.n_output_days)
  # Diffusion configurations
  noise_scheduler: "cosine" # "linear" | "cosine"
  n_steps: 1000
  beta_min: 0.001  # linear only
  beta_max: 0.020  # linear only
  # Sampling
  eta: 0.
  ensemble_size: 20
  # Training
  learning_rate: 1e-6
  train_batch_size: 4
  val_batch_size: 4
  n_epochs: 1000
  patience: 20
  tolerance: 0.
  save_frequency: 1

  # vae_wind_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/train_cesm2/vae_wind_16times/vaewind6.pt"
  # vae_mass_checkpoint:  "/scratch/zgp2ps/s2s_checkpoints/train_cesm2/vae_mass_16times/vaemass11.pt"
  # vae_thermal_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/train_cesm2/vae_thermal_16times/vaethermal15.pt"
  # vae_hydro_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/train_cesm2/vae_hydro_16times/vaehydro3.pt"
  # vae_precip_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/train_cesm2/vae_precip_4times/vaeprecip6.pt"

  # from_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/train_cesm2/diffusion_v23_cosine/diffusion24.pt"
  # saved_checkpoint_directory: "/scratch/zgp2ps/s2s_checkpoints/train_cesm2/diffusion_v23_cosine/"
  # target_path: "/scratch/zgp2ps/s2s_results/train_cesm2/diffusion_eta020/"

  vae_wind_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/train_era5/vae_wind_16times/vaewind34.pt"
  vae_mass_checkpoint:  "/scratch/zgp2ps/s2s_checkpoints/train_era5/vae_mass_16times/vaemass228.pt"
  vae_thermal_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/train_era5/vae_thermal_16times/vaethermal196.pt"
  vae_hydro_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/train_era5/vae_hydro_16times/vaehydro48.pt"
  vae_precip_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/train_era5/vae_precip_4times/vaeprecip41.pt"

  from_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/train_era5/diffusion_v23_cosine/diffusion36.pt"
  saved_checkpoint_directory: "/scratch/zgp2ps/s2s_checkpoints/train_era5/diffusion_v23_cosine/"
  target_path: "/scratch/zgp2ps/s2s_results/train_era5/diffusion_eta000/"
