cesm2:

  device: "cuda"
  root: "/scratch/zgp2ps/cesm2/data"
  # fixed configs
  input_vars: [
    "U200", "V200",
    "U500", "V500", "OMEGA500",
    "U850", "V850",
    "Z200", "Z850", "Z500",
    "FLUT", "TS", "PSL",
    "PRECT",
  ] # order matters
  output_vars: ["PRECT"]
  resolution: [192, 288]
  sim_ids: [
    # Boundary condition: BHISTsmbb
    "1011.001",
    "1031.002",
    "1051.003",
    "1071.004",
    "1091.005",
    "1111.006",
    "1131.007",
    "1151.008",
    "1171.009",
    "1191.010",
    "1231.011",
    "1251.011",
    "1281.011",
    "1301.011",
    # Boundary condition: BHISTcmip6
    "1001.001",
    "1021.002",
    "1041.003",
    "1061.004",
    "1081.005",
    "1101.006",
    "1121.007",
    "1141.008",
    "1161.009",
    "1181.010",
    "1231.001",
    "1251.001",
    "1281.001",
    "1301.001",
  ]
  # modifiable configs:
  train_start_year: 1950
  train_end_year: 2000
  val_start_year: 2001
  val_end_year: 2010
  test_start_year: 2011
  test_end_year: 2014

  n_input_days: 28
  n_lead_days: 21
  n_output_days: 7
  n_step_days: 7
  climatological_window_size: 15

  train_write_directory: "/scratch/zgp2ps/cesm2/tensors/train"
  val_write_directory: "/scratch/zgp2ps/cesm2/tensors/val"
  test_write_directory: "/scratch/zgp2ps/cesm2/tensors/test"
  detrender_state_directory: "/scratch/zgp2ps/cesm2/tensors/detrender"
  climatology_state_directory: "/scratch/zgp2ps/cesm2/tensors/climatology"


era5:

  # TODO: work in progress
  device: "cuda"
  zip_root: "/scratch/zgp2ps/era5/raw"
  array_root: "/scratch/zgp2ps/era5/arrays"

  # fixed configs
  input_vars: [
    "u_200", "v_200",
    "u_500", "v_500", "w_500",
    "u_850", "v_850",
    "z_200", "z_500", "z_850",
    "avg_tnlwrf", "t2m", "msl",
    "tp",
  ] # order matters
  output_vars: ["tp"]
  resolution: [192, 288]
  sim_ids: ["reanalysis"]

  train_start_year: 1940
  train_end_year: 2010
  val_start_year: 2011
  val_end_year: 2020
  test_start_year: 2021
  test_end_year: 2024

  n_input_days: 28
  n_lead_days: 21
  n_output_days: 7
  n_step_days: 7
  climatological_window_size: 15

  train_write_directory: "/scratch/zgp2ps/era5/tensors/train"
  train_metadata_directory: "/scratch/zgp2ps/era5/tensors/train/metadata"
  val_write_directory: "/scratch/zgp2ps/era5/tensors/val"
  val_metadata_directory: "/scratch/zgp2ps/era5/tensors/val/metadata"
  test_write_directory: "/scratch/zgp2ps/era5/tensors/test"
  test_metadata_directory: "/scratch/zgp2ps/era5/tensors/test/metadata"
  detrender_state_directory: "/scratch/zgp2ps/era5/tensors/detrender"
  climatology_state_directory: "/scratch/zgp2ps/era5/tensors/climatology"


cnn:

  device: "cuda"
  in_features: 14
  out_features: 1
  embedding_dim: 1024
  n_hidden_layers: 8

  learning_rate: 1e-6
  train_batch_size: 4
  val_batch_size: 1
  
  n_epochs: 1000
  patience: 10
  tolerance: 0.
  save_frequency: 1

  from_checkpoint: ".cnn_checkpoints/cnn22.pt"
  saved_checkpoint_directory: ".cnn_checkpoints"
  

unet:

  device: "cuda"
  in_features: 14
  out_features: 1
  embedding_dim: 512

  learning_rate: 1e-5
  train_batch_size: 8
  val_batch_size: 8
  n_epochs: 1000
  patience: 10
  tolerance: 0.
  save_frequency: 1

  from_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/unet512/unet12.pt"
  saved_checkpoint_directory: "/scratch/zgp2ps/s2s_checkpoints/unet512"
  

vit:

  device: "cuda"
  in_features: 14
  out_features: 1
  embedding_dim: 2048
  patch_size: 16
  n_heads: 8
  n_transformer_layers: 6
  dropout: 0.1

  learning_rate: 1e-5
  train_batch_size: 16
  val_batch_size: 1
  n_epochs: 1000
  patience: 10
  tolerance: 0.
  save_frequency: 1

  from_checkpoint: null
  saved_checkpoint_directory: ".vit_checkpoints"


vae-wind:

  device: "cuda"
  latent_dim: 28
  hidden_dim: 256
  n_scaling_blocks: 3
  n_convstack_layers: 3
  n_convhead_layers: 2

  lambda: 0.999
  learning_rate: 1e-6
  train_batch_size: 32
  val_batch_size: 32
  n_epochs: 1000
  patience: 10
  tolerance: 0.
  save_frequency: 1

  from_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/vae_wind_16times/vae7.pt"
  saved_checkpoint_directory: "/scratch/zgp2ps/s2s_checkpoints/vae_wind_16times"


vae-geopotential:

  device: "cuda"
  latent_dim: 12
  hidden_dim: 128
  n_scaling_blocks: 3
  n_convstack_layers: 3
  n_convhead_layers: 2

  lambda: 0.999
  learning_rate: 1e-6
  train_batch_size: 64
  val_batch_size: 64
  n_epochs: 1000
  patience: 10
  tolerance: 0.
  save_frequency: 1

  from_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/vae_geopotential_16times/vae41.pt"
  saved_checkpoint_directory: "/scratch/zgp2ps/s2s_checkpoints/vae_geopotential_16times"


vae-thermaldynamic:

  device: "cuda"
  latent_dim: 12
  hidden_dim: 128
  n_scaling_blocks: 3
  n_convstack_layers: 3
  n_convhead_layers: 2

  lambda: 0.999
  learning_rate: 1e-7
  train_batch_size: 64
  val_batch_size: 64
  n_epochs: 1000
  patience: 10
  tolerance: 0.
  save_frequency: 1

  from_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/vae_thermaldynamic_16times/vae19.pt"
  saved_checkpoint_directory: "/scratch/zgp2ps/s2s_checkpoints/vae_thermaldynamic_16times"


vae-precipitation:

  device: "cuda"
  latent_dim: 32
  hidden_dim: 256
  n_scaling_blocks: 3
  n_convstack_layers: 3
  n_convhead_layers: 2

  lambda: 0.999
  learning_rate: 1e-6
  train_batch_size: 64
  val_batch_size: 64
  n_epochs: 1000
  patience: 10
  tolerance: 0.
  save_frequency: 1

  from_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/vae_precipitation_16times/vae16.pt"
  saved_checkpoint_directory: "/scratch/zgp2ps/s2s_checkpoints/vae_precipitation_16times"


diffusion:

  device: "cuda"
  target_dim: 32  # fixed, vae-precipitation.latent_dim
  condition_dim: 2352 # fixed, (vae-wind.latent_dim + vae-geopotential.latent_dim + vae-thermaldynamic.latent_dim + vae-precipitation.latent_dim) * n_condition_days
  n_condition_days: 28  # fixed, dataset.n_input_days
  step_dim: 64
  day_dim: 64
  # Unet configurations
  down_hidden_dims: [2048, 512]
  down_out_dims: [256, 256]
  mid_hidden_dims: [512, 512]
  mid_out_dims: [256, 256]
  up_hidden_dims: [512, 512]
  up_out_dims: [256, 256]

  n_layers_per_scaling_block: 8
  n_layers_per_mid_block: 4
  n_attention_heads: 1
  switch_ratio: 0.3    # p(condition_switch=off)
  # Diffusion configurations
  noise_scheduler: "cosine" # "linear" | "cosine"
  n_steps: 1000
  beta_min: 0.001  # linear only
  beta_max: 0.015  # linear only
  # Sampling
  eta: 0.
  # Training
  learning_rate: 1e-5
  train_batch_size: 4
  val_batch_size: 4
  n_epochs: 1000
  patience: 20
  tolerance: 0.
  save_frequency: 1

  wind_vae_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/vae_wind_16times/vae7.pt"
  geopotential_vae_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/vae_geopotential_16times/vae41.pt"
  thermaldynamic_vae_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/vae_thermaldynamic_16times/vae19.pt"
  precipitation_vae_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/vae_precipitation_16times/vae16.pt"
  from_checkpoint: "/scratch/zgp2ps/s2s_checkpoints/diffusion_v10/diffusion16.pt"
  saved_checkpoint_directory: "/scratch/zgp2ps/s2s_checkpoints/diffusion_v10"

